name: Build, Test, and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform and AWS
        uses: ./.github/actions/terraform-setup

      - name: Terraform Init
        run: terraform init

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Terraform and AWS
        uses: ./.github/actions/terraform-setup

      - name: Terraform Validate
        run: terraform validate

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Terraform and AWS
        uses: ./.github/actions/terraform-setup

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
